version: '3.5'
services:
  traefik:
    image: docker.pkg.github.com/tonywangcn/traefik/traefik:dev
    container_name: traefik
    ports:
      - 9090:9090
    # env_file: dev.env
    volumes:
      - "./rule.toml:/etc/rules/rule.toml"
      - "./:/go/src/github.com/containous/traefik"
    working_dir: /go/src/github.com/containous/traefik/
    command: ["tail", "-f", "/dev/null"]
    restart: on-failure:5

  whoami1:
    container_name: whoami1
    ports:
      - 9001:80
    image: emilevauge/whoami