################################################################
# Global configuration
################################################################

[global]
  checkNewVersion = false
  sendAnonymousUsage = false

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":9090"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]
  insecure = true
  dashboard = true
  debug = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################
[providers.file]
  directory = "/etc/rules/"
  # filename = "/etc/rules/rule.toml"
  #directory = "/path/to/config/" # You could have multiple .toml files in a directory (and recursively in its sub-directories):
  watch = true